controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

test:
    path: /test #Path qu'on retrouve dans l'url
    controller: App\Controller\TestController::index #nom du controlleur à charger avec la méthode utilisé