controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: / #Path qu'on retrouve dans l'url
    controller: App\Controller\HomeController::index #nom du controlleur à charger avec la méthode utilisé